<Project>

  <PropertyGroup>
	<Product>EventForging</Product>
    <Copyright>Piotr Bejger</Copyright>
    <Authors>Piotr Bejger</Authors>
    <Company>Piotr Bejger</Company>
	<Description>EventForging is free, open-source .NET framework for event sourced applications.</Description>
    <RepositoryUrl>https://github.com/piotr07da/EventForging</RepositoryUrl>
    <PackageTags>EventForging; event; events; eventsourcing; eventdriven;</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
	<PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
  </PropertyGroup>

  <PropertyGroup>
    <LangVersion>latest</LangVersion>
	<Nullable>enable</Nullable>
	<ImplicitUsings>enable</ImplicitUsings>
	<GenerateDocumentationFile>true</GenerateDocumentationFile>
	<NoWarn>$(NoWarn);1573;1591</NoWarn>
	<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

</Project>
